# @name get-prompts
GET http://localhost:3333/prompts

###
# @name upload-videos
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name create-transcription
POST http://localhost:3333/videos/6a071702-4b06-47b2-b5d9-2faee68971de/transcription
Content-Type: application/json

{
  "prompt": "falling in love, wise, sin"
}

###
# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "6a071702-4b06-47b2-b5d9-2faee68971de",
  "temperature": 0,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}